### ISSUE TITLE
FR: Add support for pattern substitutions

### ISSUE THREAD

**Issue by ofek** [hynek/hatch-fancy-pypi-readme#9]
I'm seeing things like [this](https://github.com/gradio-app/gradio/blob/v3.2/setup.py#L11-L13) frequently:

```python
# Replace relative paths to images with absolute paths
long_description = re.sub("website/homepage/", "https://raw.githubusercontent.com/gradio-app/gradio/main/website/homepage/", long_description)
long_description = re.sub(r"demo/([\S]*.gif)", r"https://raw.githubusercontent.com/gradio-app/gradio/main/demo/\g<1>", long_description)
```

maybe:

```toml
[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
find = "website/homepage/"
replace = "https://raw.githubusercontent.com/gradio-app/gradio/main/website/homepage/"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
find = 'demo/([\S]*.gif)'
replace = 'https://raw.githubusercontent.com/gradio-app/gradio/main/demo/\g<1>'
```
